import { isArabic } from "../helper/language";

export const Texts = {
  filter: ["تصفية", "Filter"],
  sort: ["ترتيب حسب", "Sort by"],
  submit: ["تأكيد", "Submit"],
  newArrival: ["وصل حديثاً", "New arrival"],
  mostSold: ["الأكثر مبيعاً", "Most sold"],
  favourites: ["المفضلات", "Favourites"],
  priceFromLowToHigh: ["السعر من الأقل الى الأعلى", "Price from low to high"],
  priceFromHighToLow: ["السعر من الأعلى الى الأقل", "Price from high to low"],
  sales: ["التنزيلات", "Sales"],
  mostPopular: ["الأكثر شهرة", "Most popular"],
  lessThan: ["اقل من", "Less than"],
  from: ["من", "From"],
  to: ["الى", "To"],
  moreThan: ["اكثر من", "More than"],
  seeSimilarProducts: ["مشاهدة منتجات مشابهة", "See similar products"],
  reviewes: ["تعليقات", "Reviewes"],
  productIsBought: ["تم شراء المنتج", "Product Is bought"],
  timesToday: ["مره خلال اليوم", "Times today"],
  giftWithOrder: ["هدية مع الطلب", "Gift with order"],
  sizeGuide: ["دليل المقاسات", "Size guide"],
  chooseColor: ["اختر اللون :", "Choose color :"],
  chooseSize: ["اختر المقاس :", "Choose size :"],
  availableInStore: ["متوفر في المخزون", "Available in store"],
  splitYourBillOn4InstallmentsWithoutInterest: [
    "قسم فاتورتك على ٤ دفعات من غير فوائد ",
    "Split on 4 installments without interest",
  ],
  chooseTamaraInPaymentPage: [
    "اختر تمارا في صفحة الدفع",
    "Choose tamara for payment",
  ],
  chooseTabbyInPaymentPage: [
    "اختر تابي في صفحة الدفع",
    "Choose tabby for payment",
  ],
  learnMore: ["اعرف المزيد", "Learn more"],
  freeReturn: ["ارجاع مجاني", "Free Return"],
  description: ["الوصف", "Description"],
  thereviewes: ["التقييمات", "Reviews"],
  watchAll: ["مشاهدة الكل", "Watch all"],
  small: ["صغير", "Small"],
  large: ["كبير", "Large"],
  perfectFit: ["المقاس مضبوط", "Perfect fit"],
  isTheProductSizeAppropriate: [
    "هل مقاس المنتج مناسب ؟",
    "Is the product size appropriate ?",
  ],
  youMayAlsoLike: ["قد يعجبك ايضاً", "You may also like"],
  similarProducts: ["منتجات مشابهه", "Similar products"],
  recommended: ["موصى بها", "Recommended"],
  addToCart: ["اضف للسلة", "Add to cart"],
  pleaseNotifyMeWhenItIsAvailable: [
    "الرجاء اخطاري حال توفره",
    "Please notify me when it is available",
  ],
  myWishList: ["مفضلاتي", "My wishlist"],
  cart: ["حقيبة التسوق", "Cart"],
  add: ["اضف", "Add"],
  toGetFreeShipping: ["لتحصلي على شحن مجاني", "to get free shipping"],
  continueShopping: ["متابعه التسوق", "Continue shopping"],
  thereAre: ["يوجد", "There are"],
  thereIs: ["يوجد", "There is"],
  inStore: ["في المخزن", "In store"],
  outOfStock: ["نفذ من المخزون", "Out of stock"],
  color: ["اللون", "Color"],
  size: ["المقاس", "Size"],
  remove: ["حذف", "Remove"],
  addToWishList: ["اضف للمفضة", "Add to wish list"],
  wrapProductAsGift: ["تغليف المنتج كهدية", "Wrap product as gift"],
  wrapCartAsGift: ["تغليف السلة كهدية", "Wrap cart as gift"],
  orderDetails: ["تفاصيل الطلب", "Order details"],
  confirmOrder: ["اتمام الطلب", "Confirm order"],
  total: ["المجموع", "Total"],
  includingVat: ["شامل ضريبة القيمة المضافة", "Including VAT"],
  HaveACoupon: ["لديك كوبون خصم؟", "Have a coupon ?"],
  coupons: ["الكوبونات", "Coupons"],
  myPoints: ["نقاطي", "My points"],
  HaveGiftCard: ["لديك قسيمه هدايا ؟", "Have gift card ?"],
  applyCoupon: ["تطبيق الكوبون", "Apply coupon"],
  coupon: ["الكوبون", "Coupon"],
  apply: ["تطبيق", "Apply"],
  enterTheCouponCode: ["ادخل كوبون الخصم", "Enter the coupon code"],
  enterThePoints: ["ادخل النقاط", "Enter the Points"],
  giftCards: ["قسايم الهدايا", "Gift Cards"],
  enterCardCode: ["ادخل كود القسيمه", "Enter card code"],
  congratulationsYouGotADiscount: [
    "مبروك حصلت على خصم",
    "Congratulations you got a discount",
  ],
  congratulationYouHaveApplied: [
    "مبروك لقد قمت بتطبيق",
    "Congratulations you have applied",
  ],
  myAccount: ["حسابي", "My account"],
  accountInfo: ["معلومات الحساب", "Account info"],
  myOrders: ["طلباتي", "My orders"],
  return: ["الإرجاع", "Return"],
  wallet: ["المحفظة", "Wallet"],
  address: ["العنوان", "Address"],
  settings: ["الاعدادات", "Settings"],
  whatAreYouLookingFor: ["وش اللي فخاطرك ؟", "what are you looking for?"],
  language: ["اللغة", "Language"],
  contactUs: ["تواصل معنا", "Contact us"],
  login: ["تسجيل الدخول", "Login"],
  skip: ["تخطي", "Skip"],
  welcome: ["مرحباً بك", "Welcome"],
  loginWithYourPhoneNumberOrThroughEmail: [
    "سجلي دخولك عن طريق رقم هاتفك اوعن طريق الايميل",
    "Login with your phone number or through email.",
  ],
  loginWith: ["دخول عن طريق", "Login with"],
  yourPhoneNumber: ["رقم جوالك", "Your phone number"],
  signIn: ["سجل دخولي", "Sign in"],
  phoneNumberIsNotValid: ["رقم الهاتف غير صالح", "Phone number is not valid"],
  pointsAreNotValid: ["النقاط غير صالحة", "Points are not valid"],
  phoneNumberShouldStartWith: [
    `يجب ان يبدأ رقم الهاتف ب`,
    `Phone number should start with`,
  ],
  phoneNumberLengthShouldBe: [
    "يجب ان يتكون طول رقم الهاتف من",
    "Phone number length shouldn be",
  ],
  numbers: ["أرقام", "Numbers"],
  verify: ["تحقق", "Verify"],
  verifyingOTP: ["التحقق من OTP", "Verifying OTP"],
  weWillSendYouAnOTPOn: [
    "سوف نرسل لك رمز التحقق على",
    "We will send you an OTP on",
  ],
  phoneNumber: ["رقم الجوال", "Phone number"],
  emailIsNotValid: ["البريد الالكتروني غير صالح", "Email is not valid"],
  firstName: ["الاسم الاول", "First name"],
  lastName: ["اسم العائلة", "Last name"],
  email: ["البريد الالكتروني", "Email"],
  gender: ["الجنس", "Gender"],
  male: ["ذكر", "Male"],
  female: ["انثى", "Female"],
  dateOfBirth: ["تاريخ الميلاد", "Date of birth"],
  logout: ["تسجيل الخروج", "Logout"],
  confirmAccountInfo: ["تأكيد معلومات الحساب", "Confirm account info"],
  showCart: ["عرض حقيبه التسوق", "Show cart"],
  mySuggestionsForYou: ["مقترحاتي لك", "My Suggestions For You"],
  addedSuccessfullyToYourCart: [
    "تم اضافته بنجاح الى حقيبه تسوقك",
    "Added Successfully To Your cart",
  ],
  couponCodeIsRequired: ["كود الكوبون مطلوب", "Coupon code is required"],
  pointsAreRequired: ["النقاط مطلوبة", "Points are required"],
  giftCardCodeIsRequired: ["كود الهدية مطلوب", "Gift card code is required"],
  youDeservedFreeShipping: [
    "لقد استحققت شحن مجاني",
    "You deserved free shipping",
  ],
  myAddress: ["عنواني", "My address"],
  addNewAddress: ["اضافة عنوان جديد", "Add new address"],
  enterYourAddress: ["ادخل عنوانك", "Enter your location"],
  congratsOnYourOrder: ["مبروك عليك الطلب", "Congrats on your order"],
  orderSuccessfullyPlaced: ["تم الطلب بنجاح", "Order successfully placed"],
  orderNumber: ["رقم الطلب", "Order number"],
  reviewAndContinueShopping: [
    "تقيم وتابع التسوق",
    "Review and continue shopping",
  ],
  saveAddress: ["حفظ العنوان", "Save address"],
  addtionalInfo: ["معلومات اضافية", "Addtional Info"],
  toGetItOn: ["لتحصل عليه", "To Get it on"],
  deliverTo: ["توصيل الى", "Deliver to"],
  changeAddress: ["تغيير العنوان", "Change address"],
  choosePaymentMethod: ["اختر طريقة الدفع", "Choose payment method"],
  addCard: ["اضف بطاقة", "Add card"],
  creditCardisnotValid: [
    "بطاقة الائتمان غير صالحة",
    "Credit card isn't valid",
  ],
  cardNumber: ["رقم البطاقه", "Card number"],
  expiryMonth: ["شهر الانتهاء", "Expiry month"],
  expiryYear: ["سنة الانتهاء", "Expiry year"],
  cvv: ["CVV", "CVV"],
  confirm: ["تأكيد", "confirm"],
  cardInfo: ["معلومات البطاقة", "Card info"],
  youRecentlySearchedFor: ["لقد بحثت مؤخرا عن", "You recently searched for"],
  sortBy: ["ترتيب حسب", "Sort by"],
  addedToWishList: ["تمت الاضافة الى المفضلة", "Added to wish list"],
  sorrySomethingWentWrongWithYourPayment: [
    "عذرا حدث خطأ ما في عملية الدفع",
    "Sorry, something went wrong with your payment",
  ],
  dayOfBirth: ["يوم ميلادك", "Day of Bith"],
  monthOfBirth: ["شهر ميلادك", "Month of Bith"],
  yourGiftOnUs: ["هديتك علينا", "Your gift on us"],
  chooseGiftWrapperType: ["اضف نوع التغليف", "Choose gift wrapper type"],
  giftWrapperIsAdded: ["تم اضافة تغليف الهدايا 😊", "gift wrapper is added 😊"],
  pleaseChooseColor: ["الرجاء تحديد اللون", "Please, choose color"],
  pleaseChooseSize: ["الرجاء تحديد المقاس", "Please, choose size"],
  comingSoon: ["ستتوفر قريبا", "Coming soon"],
  date: ["التاريخ", "Date"],
  productsNumber: ["عدد المنتجات", "Products number"],
  viewDetails: ["مشاهدة التفاصيل", "View details"],
  soldOut: ["بيعت بالكامل", "Sold out"],
  soldOutPleaseRemoveTheItemToContinue: [
    "بيعت بالكامل الرجاء ازالة المنتج للمتابعة",
    "Sold Out Please, Remove the item to continue",
  ],
  couponCodeIsNotValid: ["كود الكوبون غير صالح", "Coupon code is not valid"],
  cardCodeIsNotValid: ["كود القسيمة غير صالح", "Card code is not valid"],
  sorryWecouldnotFindThisPage: [
    "عذرا لا يمكننا العثور على هذه الصفحة",
    "Sorry, we could not find this page",
  ],
  orderWithin: ["قم بالطلب خلال", "Order within"],
  hour: ["ساعة", "Hour"],
  orderInfo: ["معلومات الطلب", "Order info"],
  status: ["الحالة", "Status"],
  followOrder: ["متابعة الطلب", "Follow order"],
  shippingInfo: ["معلومات الشحن", "Shipping info"],
  paymentMethod: ["طريقة الدفع", "Payment method"],
  orderProducts: ["منتجات الطلب", "Order products"],
  available: ["متوفر", "Available"],
  pleaseAddWrappingType: [
    "الرجاء اضافة نوع التغليف",
    "Please Add wrapping type",
  ],
  pleaseAddYourAddress: ["الرجاء اضافة عنوانك", "Please Add your address"],
  pleaseChoosePaymentMethod: [
    "الرجاء تحديد طريقة الدفع",
    "Please choose payment method",
  ],
  country: ["الدولة", "Country"],
  region: ["المنطقة", "Region"],
  city: ["المدينة", "City"],
  district: ["الحي", "District"],
  street: ["الشارع", "Street"],
  homeDetails: ["تفاصيل المنزل", "Home details"],
  pleaseChooseYourCountry: [
    "الرجاء تحديد الدولة",
    "Please, Choose your Country",
  ],
  pleaseChooseYourRegion: [
    "الرجاء تحديد المنطقة",
    "Please, Choose your Region",
  ],
  pleaseChooseYourCity: ["الرجاء تحديد المدينة", "Please, Choose your city"],
  pleaseChooseYourDistrict: [
    "الرجاء تحديد الحي",
    "Please, Choose your District",
  ],
  pleaseChooseYourStreet: ["الرجاء تحديد الشارع", "Please, Choose your Street"],
  pleaseChooseYourHomeDetails: [
    "الرجاء تحديد تفاصيل المنزل",
    "Please, Choose your Home Details",
  ],
  searchCountry: ["ابحث عن دولتك", "Search country"],
  searchCity: ["ابحث عن مدينتك", "Search city"],
  searchRegion: ["ابحث عن منطقتك", "Search region"],
  searchDistrict: ["ابحث عن الحي", "Search district"],
  selectCountry: ["اختر دولتك", "Select country"],
  selectCity: ["اختر مدينتك", "Select city"],
  selectRegion: ["اختر منطقتك", "Select region"],
  selectDistrict: ["اختر الحي", "Select district"],
  noCountryFound: ["لم يتم العثور على دولة", "No country found"],
  noCityFound: ["لم يتم العثور على مدينة", "No city found"],
  noRegionFound: ["لم يتم العثور على منطقة", "No region found"],
  noDistrictFound: ["لم يتم العثور على الحي", "No district found"],
  payment: ["الدفع", "Payment"],
  finishBuyingThisProductToGet: [
    "اتمم شراء المنتج لتحصل على",
    "Finish buying this product to get",
  ],
  completeThisOrderToGet: [
    "اكمل الطلب لتحصل على",
    "Complete this order to get",
  ],
  point: ["نقطة", "Point"],
  applyMyPoints: ["تطبيق نقاطي", "Apply my points"],
  pointsHistory: ["تاريخ النقاط", "Points history"],
  products: ["منتجات", "Products"],
  downloadTheApp: ["حمل التطبيق", "Download the app"],
  leftInStock: ["متبقي في المخزون", "Left in stock"],
  forQuestionsAndComplaints: [
    "للاستفسارات والشكاوي",
    "For questions and complaints",
  ],
  followUsOn: ["تابعنا على", "Follow us on"],
  overView: ["نظرة عامة", "Over view"],
  specifications: ["المواصفات", "Specifications"],
  highlights: ["المزيد من التفاصيل", "Highlights"],
};
export function getText({
  storeCode,
  text,
}: {
  storeCode: string;
  text: string[];
}): string {
  return isArabic(storeCode) ? text[0] : text[1];
}
